export const COURSES = [
  {
    id: "digital-marketing-100",
    title: "100 Days Digital Marketing Mastery",
    shortTitle: "Digital Marketing",
    emoji: "🚀",
    description:
      "Master SEO, PPC, Social Ads, Content, Email, Analytics & more",
    duration: "100 days",
    difficulty: "Beginner → Advanced",
    gradient: ["#6366f1", "#8b5cf6"],
    phases: [
      {
        name: "SEO Fundamentals",
        tasks: [
          { d: 1, task: "Understand how search engines crawl, index & rank pages", cat: "SEO", lvl: "Beginner" },
          { d: 2, task: "Learn keyword research basics — search intent & volume", cat: "SEO", lvl: "Beginner" },
          { d: 3, task: "Hands-on: Use Google Keyword Planner & Ubersuggest", cat: "SEO", lvl: "Beginner" },
          { d: 4, task: "Study long-tail vs short-tail keywords strategy", cat: "SEO", lvl: "Beginner" },
          { d: 5, task: "Learn about SERP features — snippets, PAA, local pack", cat: "SEO", lvl: "Beginner" },
          { d: 6, task: "Competitor keyword analysis with SEMrush / Ahrefs", cat: "SEO", lvl: "Beginner" },
          { d: 7, task: "Create a keyword map for a sample project", cat: "SEO", lvl: "Beginner" },
          { d: 8, task: "Quiz & review: SEO fundamentals checkpoint", cat: "SEO", lvl: "Beginner" },
        ],
      },
      {
        name: "On-Page SEO",
        tasks: [
          { d: 9, task: "Title tags, meta descriptions & header hierarchy", cat: "SEO", lvl: "Beginner" },
          { d: 10, task: "URL structure & internal linking best practices", cat: "SEO", lvl: "Beginner" },
          { d: 11, task: "Image optimization — alt text, compression, WebP", cat: "SEO", lvl: "Beginner" },
          { d: 12, task: "Content optimization for target keywords", cat: "SEO", lvl: "Intermediate" },
          { d: 13, task: "Schema markup & structured data basics", cat: "SEO", lvl: "Intermediate" },
          { d: 14, task: "Hands-on: Audit a live website for on-page issues", cat: "SEO", lvl: "Intermediate" },
          { d: 15, task: "E-E-A-T principles & content quality signals", cat: "SEO", lvl: "Intermediate" },
          { d: 16, task: "Mini-project: Optimize 5 pages of a sample site", cat: "SEO", lvl: "Intermediate" },
        ],
      },
      {
        name: "Technical SEO",
        tasks: [
          { d: 17, task: "Site speed & Core Web Vitals optimization", cat: "SEO", lvl: "Intermediate" },
          { d: 18, task: "Mobile-first indexing & responsive design", cat: "SEO", lvl: "Intermediate" },
          { d: 19, task: "XML sitemaps & robots.txt configuration", cat: "SEO", lvl: "Intermediate" },
          { d: 20, task: "Canonical tags, redirects & duplicate content", cat: "SEO", lvl: "Intermediate" },
          { d: 21, task: "Crawl budget optimization & log file analysis", cat: "SEO", lvl: "Advanced" },
          { d: 22, task: "HTTPS, security headers & site architecture", cat: "SEO", lvl: "Intermediate" },
          { d: 23, task: "Hands-on: Full technical audit with Screaming Frog", cat: "SEO", lvl: "Advanced" },
          { d: 24, task: "Checkpoint: Technical SEO audit report", cat: "SEO", lvl: "Advanced" },
        ],
      },
      {
        name: "Off-Page SEO",
        tasks: [
          { d: 25, task: "Backlink fundamentals — DA, PA, link types", cat: "SEO", lvl: "Intermediate" },
          { d: 26, task: "Guest posting & outreach strategy", cat: "SEO", lvl: "Intermediate" },
          { d: 27, task: "Broken link building & resource page tactics", cat: "SEO", lvl: "Advanced" },
          { d: 28, task: "Local SEO — Google Business Profile optimization", cat: "SEO", lvl: "Intermediate" },
          { d: 29, task: "Online reputation & review management", cat: "SEO", lvl: "Intermediate" },
          { d: 30, task: "Mini-project: Build 10 quality backlinks plan", cat: "SEO", lvl: "Advanced" },
        ],
      },
      {
        name: "PPC & Google Ads",
        tasks: [
          { d: 31, task: "PPC fundamentals — CPC, CPM, CPA, Quality Score", cat: "PPC", lvl: "Beginner" },
          { d: 32, task: "Google Ads account structure — campaigns, ad groups", cat: "PPC", lvl: "Beginner" },
          { d: 33, task: "Keyword match types & negative keywords", cat: "PPC", lvl: "Beginner" },
          { d: 34, task: "Writing high-CTR ad copy & responsive search ads", cat: "PPC", lvl: "Beginner" },
          { d: 35, task: "Ad extensions — sitelinks, callouts, structured snippets", cat: "PPC", lvl: "Intermediate" },
          { d: 36, task: "Bidding strategies — manual, enhanced, target CPA/ROAS", cat: "PPC", lvl: "Intermediate" },
          { d: 37, task: "Landing page optimization for PPC campaigns", cat: "PPC", lvl: "Intermediate" },
          { d: 38, task: "Google Ads conversion tracking setup", cat: "PPC", lvl: "Intermediate" },
          { d: 39, task: "Remarketing & RLSA campaigns", cat: "PPC", lvl: "Intermediate" },
          { d: 40, task: "Shopping Ads & Google Merchant Center", cat: "PPC", lvl: "Intermediate" },
          { d: 41, task: "Performance Max campaigns deep dive", cat: "PPC", lvl: "Advanced" },
          { d: 42, task: "A/B testing ads & ad rotation strategies", cat: "PPC", lvl: "Intermediate" },
          { d: 43, task: "Budget allocation & campaign optimization", cat: "PPC", lvl: "Advanced" },
          { d: 44, task: "Google Ads scripts & automation basics", cat: "PPC", lvl: "Advanced" },
          { d: 45, task: "Project: Launch a mock Google Ads campaign", cat: "PPC", lvl: "Advanced" },
        ],
      },
      {
        name: "Social Media Ads",
        tasks: [
          { d: 46, task: "Facebook/Meta Ads Manager setup & structure", cat: "Ads", lvl: "Beginner" },
          { d: 47, task: "Facebook audience targeting — custom, lookalike, saved", cat: "Ads", lvl: "Intermediate" },
          { d: 48, task: "Instagram Ads — formats, reels, stories, carousels", cat: "Ads", lvl: "Intermediate" },
          { d: 49, task: "Facebook Pixel & Conversions API setup", cat: "Ads", lvl: "Intermediate" },
          { d: 50, task: "LinkedIn Ads — B2B targeting & lead gen forms", cat: "Ads", lvl: "Intermediate" },
          { d: 51, task: "Twitter/X Ads & YouTube Ads overview", cat: "Ads", lvl: "Intermediate" },
          { d: 52, task: "TikTok Ads — creative best practices", cat: "Ads", lvl: "Intermediate" },
          { d: 53, task: "Social media ad copywriting & creative design", cat: "Ads", lvl: "Intermediate" },
          { d: 54, task: "Retargeting across social platforms", cat: "Ads", lvl: "Advanced" },
          { d: 55, task: "Project: Create a multi-platform ad campaign plan", cat: "Ads", lvl: "Advanced" },
        ],
      },
      {
        name: "Display & Video Ads",
        tasks: [
          { d: 56, task: "Google Display Network — targeting & placements", cat: "Ads", lvl: "Intermediate" },
          { d: 57, task: "Banner ad design principles & responsive ads", cat: "Ads", lvl: "Intermediate" },
          { d: 58, task: "YouTube Ads — TrueView, bumper, discovery formats", cat: "Ads", lvl: "Intermediate" },
          { d: 59, task: "Video ad scripting & production basics", cat: "Ads", lvl: "Intermediate" },
          { d: 60, task: "Programmatic advertising & DSP overview", cat: "Ads", lvl: "Advanced" },
          { d: 61, task: "Connected TV & OTT advertising trends", cat: "Ads", lvl: "Advanced" },
          { d: 62, task: "Checkpoint: Paid media strategy document", cat: "Ads", lvl: "Advanced" },
        ],
      },
      {
        name: "Content Marketing",
        tasks: [
          { d: 63, task: "Content strategy framework & content pillars", cat: "Content", lvl: "Beginner" },
          { d: 64, task: "Blog writing for SEO — structure, length, readability", cat: "Content", lvl: "Beginner" },
          { d: 65, task: "Content calendar creation & planning tools", cat: "Content", lvl: "Beginner" },
          { d: 66, task: "Visual content — infographics, carousels, thumbnails", cat: "Content", lvl: "Intermediate" },
          { d: 67, task: "Video content strategy — YouTube, shorts, reels", cat: "Content", lvl: "Intermediate" },
          { d: 68, task: "Podcast & audio content marketing", cat: "Content", lvl: "Intermediate" },
          { d: 69, task: "Content distribution & amplification channels", cat: "Content", lvl: "Intermediate" },
          { d: 70, task: "Content repurposing — one piece, 10 formats", cat: "Content", lvl: "Intermediate" },
          { d: 71, task: "AI tools for content creation & scaling", cat: "Content", lvl: "Advanced" },
          { d: 72, task: "Project: Build a 30-day content calendar", cat: "Content", lvl: "Advanced" },
        ],
      },
      {
        name: "Email Marketing",
        tasks: [
          { d: 73, task: "Email marketing fundamentals & platform setup", cat: "Email", lvl: "Beginner" },
          { d: 74, task: "List building strategies & lead magnets", cat: "Email", lvl: "Beginner" },
          { d: 75, task: "Email copywriting — subject lines, body, CTAs", cat: "Email", lvl: "Intermediate" },
          { d: 76, task: "Email design — templates, responsive layouts", cat: "Email", lvl: "Intermediate" },
          { d: 77, task: "Automation workflows — welcome, nurture, win-back", cat: "Email", lvl: "Intermediate" },
          { d: 78, task: "Segmentation & personalization strategies", cat: "Email", lvl: "Intermediate" },
          { d: 79, task: "Deliverability, spam filters & compliance", cat: "Email", lvl: "Intermediate" },
          { d: 80, task: "Project: Design a 5-email nurture sequence", cat: "Email", lvl: "Advanced" },
        ],
      },
      {
        name: "Analytics & Data",
        tasks: [
          { d: 81, task: "Google Analytics 4 — setup & navigation", cat: "Analytics", lvl: "Beginner" },
          { d: 82, task: "GA4 events, conversions & custom dimensions", cat: "Analytics", lvl: "Intermediate" },
          { d: 83, task: "Google Tag Manager — tags, triggers, variables", cat: "Analytics", lvl: "Intermediate" },
          { d: 84, task: "UTM parameters & campaign tracking", cat: "Analytics", lvl: "Intermediate" },
          { d: 85, task: "Google Search Console deep dive", cat: "Analytics", lvl: "Intermediate" },
          { d: 86, task: "Looker Studio dashboard creation", cat: "Analytics", lvl: "Intermediate" },
          { d: 87, task: "Attribution models — first-click, last-click, data-driven", cat: "Analytics", lvl: "Advanced" },
          { d: 88, task: "Project: Build a marketing performance dashboard", cat: "Analytics", lvl: "Advanced" },
        ],
      },
      {
        name: "CRO",
        tasks: [
          { d: 89, task: "CRO fundamentals — funnels, heuristics, user behavior", cat: "CRO", lvl: "Intermediate" },
          { d: 90, task: "Heatmaps, session recordings & user testing tools", cat: "CRO", lvl: "Intermediate" },
          { d: 91, task: "A/B testing methodology & tools (Optimizely, VWO)", cat: "CRO", lvl: "Intermediate" },
          { d: 92, task: "Landing page optimization — above the fold, trust signals", cat: "CRO", lvl: "Advanced" },
          { d: 93, task: "Project: CRO audit & test plan for a live site", cat: "CRO", lvl: "Advanced" },
        ],
      },
      {
        name: "Advanced Strategy",
        tasks: [
          { d: 94, task: "Omnichannel marketing strategy & customer journey", cat: "Strategy", lvl: "Advanced" },
          { d: 95, task: "Marketing automation — HubSpot, Marketo overview", cat: "Strategy", lvl: "Advanced" },
          { d: 96, task: "Budget planning & ROI calculation across channels", cat: "Strategy", lvl: "Advanced" },
          { d: 97, task: "AI & emerging trends in digital marketing 2025+", cat: "Strategy", lvl: "Advanced" },
        ],
      },
      {
        name: "Capstone",
        tasks: [
          { d: 98, task: "Full digital marketing strategy for a brand", cat: "Strategy", lvl: "Advanced" },
          { d: 99, task: "Presentation & portfolio preparation", cat: "Strategy", lvl: "Advanced" },
          { d: 100, task: "Final review, certification prep & next steps", cat: "Strategy", lvl: "Advanced" },
        ],
      },
    ],
    categories: {
      SEO: "#6366f1",
      PPC: "#3b82f6",
      Ads: "#06b6d4",
      Content: "#f97316",
      Email: "#ec4899",
      Analytics: "#8b5cf6",
      CRO: "#14b8a6",
      Strategy: "#ef4444",
    },
    phaseColors: {
      "SEO Fundamentals": "#6366f1",
      "On-Page SEO": "#818cf8",
      "Technical SEO": "#a78bfa",
      "Off-Page SEO": "#c4b5fd",
      "PPC & Google Ads": "#3b82f6",
      "Social Media Ads": "#06b6d4",
      "Display & Video Ads": "#0ea5e9",
      "Content Marketing": "#f97316",
      "Email Marketing": "#ec4899",
      "Analytics & Data": "#8b5cf6",
      CRO: "#14b8a6",
      "Advanced Strategy": "#ef4444",
      Capstone: "#f59e0b",
    },
    levelColors: {
      Beginner: "#22c55e",
      Intermediate: "#f59e0b",
      Advanced: "#ef4444",
    },
  },
];
